const GLOB_SRC_EXT = '?([cm])[jt]s?(x)';

export const GLOB = {
  SRC_EXT: GLOB_SRC_EXT,
  SRC: `**/*.${GLOB_SRC_EXT}`,
  JS: '**/*.?([cm])js',
  JSX: '**/*.?([cm])jsx',
  TS: '**/*.?([cm])ts',
  TSX: '**/*.?([cm])tsx',
  JSON: '**/*.json',
  JSONC: '**/*.jsonc',
  BENCH: [`**/*.bench.${GLOB_SRC_EXT}`],
  TESTS: [
    `**/__tests__/**/*.${GLOB_SRC_EXT}`,
    `**/*.spec.${GLOB_SRC_EXT}`,
    `**/*.test.${GLOB_SRC_EXT}`,
  ],
  EXCLUDE: [
    '**/node_modules',
    '**/dist',
    '**/package-lock.json',
    '**/yarn.lock',
    '**/pnpm-lock.yaml',
    '**/bun.lockb',
    '**/output',
    '**/coverage',
    '**/temp',
    '**/.temp',
    '**/tmp',
    '**/.tmp',
    '**/.history',
    '**/.next',
    '**/.vercel',
    '**/.git',
    '**/.cache',
    '**/.output',
    '**/*.min.*',
  ],
};
