export const GLOB = {
  EXCLUDE: [
    '**/node_modules',
    '**/dist',
    '**/build',
    '**/out',
    '**/.output',
    '**/output',
    '**/coverage',
    '**/temp',
    '**/.temp',
    '**/.next',
    '**/.svelte-kit',
    '**/.nuxt',
    '**/.astro',
    '**/.cache',
    '**/.config',
    '**/.turbo',
    '**/.vercel',
    '**/.netlify',
    '**/.serverless',
    '**/.idea',
    '**/.vscode',
    '**/.upm',
    '**/pnpm-lock.yaml',
    '**/package-lock.json',
    '**/yarn.lock',
    '**/bun.lockb',
    '**/*.min.*'
  ],
  SRC: ['**/*.?([cm])[jt]s?(x)'],
  JS: ['**/*.?([cm])js?(x)'],
  TS: ['**/*.?([cm])ts?(x)'],
  REACT: ['**/*.?([cm])jsx', '**/*.?([cm])tsx'],
  MISC: [
    `**/*.spec.?([cm])[jt]s?(x)`,
    `**/*.test.?([cm])[jt]s?(x)`,
    `**/*.bench.?([cm])[jt]s?(x)`
  ]
};
